# Generated by Django 3.2.8 on 2021-10-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_remove_imgprocess_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='heatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgHeatmap', models.ImageField(upload_to='heatmap/')),
            ],
        ),
        migrations.AlterField(
            model_name='imgprocess',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
