# Generated by Django 3.2.8 on 2021-10-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20211026_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='heatmap',
            new_name='heatmapModel',
        ),
    ]
